- name: Install dependencies
  apt:
    name: "{{ item }}"
    update_cache: True
  loop: ["cron", "git", "wget", "socat"]


- name: Create git clone path
  file:
    path: "/etc/acme.sh"
    state: "directory"
    owner: "ubuntu"
    group: "ubuntu"
    mode: "0755"

- name: Git clone https://github.com/Neilpang/acme.sh
  git:
    repo: "https://github.com/Neilpang/acme.sh"
    dest: "/etc/acme.sh"
  become_user: "ubuntu"

- name: Install acme.sh
  command: >-
    ./acme.sh --install --log
    --days 60
    {{ "--accountemail " + acme_sh_account_email if acme_sh_account_email else "" }}
  args:
    chdir: "/etc/acme.sh"
    creates: "/root/.acme.sh"

- name: Create certificate path
  file:
    path: "/home/ubuntu/certs"
    state: "directory"
    owner: "ubuntu"
    group: "ubuntu"
    mode: "0755"

- name: Stop nginx
  systemd:
      name: nginx
      state: stopped

- name: Issue acme.sh certificate(s)
  command: >-
    ./acme.sh --issue -d {{ ansible_ssh_host }}
    --standalone
    --cert-file "/home/ubuntu/certs/cert.cer"
    --key-file "/home/ubuntu/certs/key.pem"
    --ca-file "/home/ubuntu/certs/ca.cer"
    --fullchain-file "/home/ubuntu/certs/fullchain.cer"
  args:
    chdir: "/etc/acme.sh"
  register: issue_result
  changed_when: issue_result.rc == 0 and "Cert success" in issue_result.stdout
  failed_when: issue_result.rc != 0 and "Domains not changed" not in issue_result.stdout

- name: Fix permissions of certificate
  file:
    path: "/home/ubuntu/certs"
    state: "directory"
    owner: "ubuntu"
    group: "ubuntu"
    mode: 0744
    recurse: yes