- name: Tune sysctl.conf
  template:
    src: sysctl.conf.j2
    dest: /etc/sysctl.conf
  become: yes
  become_user: root

- name: Refresh sysctl
  command: sysctl -p
  become: yes
  become_user: root